CC = g++
CFLAGS = -O0 -g -Wall -I include
SOURCES = TestGenerator.cpp main.cpp
HEADERS = 2Q.h TestGenerator.h
OBJECTS = $(SOURCES:.cpp=.o)

TestGenerator.o: TestGenerator.cpp TestGenerator.h
	$(CC) $(CFLAGS) TestGenerator.cpp -c -o TestGenerator.o

main.o: main.cpp
	$(CC) $(CFLAGS) main.cpp -c -o main.o

.PHONY: all
all: TestGenerator.o main.o
	$(CC) $(CFLAGS) TestGenerator.o main.o -o 2Q


.PHONY: clean
clean:
	rm -r -f $(OBJECTS)
	rm -f 2Q
	rm -r -f TestGenerator.o

